name: "netbird"

x-lockdown: &lockdown
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"
  # needed for full netbird client to manipulate routing and DNS
  cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE

services:
  client:
    image: "11notes/netbird-client:0.64.1"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      NETBIRD_PEER_NAME: "docker-client"
      NETBIRD_URL: "${NETBIRD_URL}"
      NETBIRD_SETUP_KEY: "${NETBIRD_SETUP_KEY}"
    volumes:
      - "netbird-client.etc:/netbird/etc"
    tmpfs:
      - "/run:uid=1000,gid=1000"
    networks:
      frontend:
    restart: "always"

volumes:
  netbird-client.etc:

networks:
  frontend: